---
abstract: 'Detect and eliminate stray commas in Javascript source files'
author:
  - 'Michael Langner <mila@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Nostray
requires:
  File::Next: '0'
  File::Slurp: '0'
  Getopt::Std: '0'
  JSON: '0'
  JavaScript::V8: '0'
  vars: '0'
version: '0.003'
